/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWaitingRoomRouteImport } from './routes/_authenticated.waiting-room'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedRecurrenceRouteImport } from './routes/_authenticated.recurrence'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated.records'
import { Route as AuthenticatedProceduresRouteImport } from './routes/_authenticated.procedures'
import { Route as AuthenticatedFinancialRouteImport } from './routes/_authenticated.financial'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated.appointments'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated.patients.index'
import { Route as AuthenticatedPatientsIdRouteImport } from './routes/_authenticated.patients.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWaitingRoomRoute =
  AuthenticatedWaitingRoomRouteImport.update({
    id: '/waiting-room',
    path: '/waiting-room',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecurrenceRoute = AuthenticatedRecurrenceRouteImport.update({
  id: '/recurrence',
  path: '/recurrence',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProceduresRoute = AuthenticatedProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancialRoute = AuthenticatedFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsIdRoute = AuthenticatedPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financial': typeof AuthenticatedFinancialRoute
  '/procedures': typeof AuthenticatedProceduresRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/recurrence': typeof AuthenticatedRecurrenceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/waiting-room': typeof AuthenticatedWaitingRoomRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financial': typeof AuthenticatedFinancialRoute
  '/procedures': typeof AuthenticatedProceduresRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/recurrence': typeof AuthenticatedRecurrenceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/waiting-room': typeof AuthenticatedWaitingRoomRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financial': typeof AuthenticatedFinancialRoute
  '/_authenticated/procedures': typeof AuthenticatedProceduresRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/recurrence': typeof AuthenticatedRecurrenceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/waiting-room': typeof AuthenticatedWaitingRoomRoute
  '/_authenticated/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/appointments'
    | '/dashboard'
    | '/financial'
    | '/procedures'
    | '/records'
    | '/recurrence'
    | '/settings'
    | '/waiting-room'
    | '/patients/$id'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/appointments'
    | '/dashboard'
    | '/financial'
    | '/procedures'
    | '/records'
    | '/recurrence'
    | '/settings'
    | '/waiting-room'
    | '/patients/$id'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/appointments'
    | '/_authenticated/dashboard'
    | '/_authenticated/financial'
    | '/_authenticated/procedures'
    | '/_authenticated/records'
    | '/_authenticated/recurrence'
    | '/_authenticated/settings'
    | '/_authenticated/waiting-room'
    | '/_authenticated/patients/$id'
    | '/_authenticated/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/waiting-room': {
      id: '/_authenticated/waiting-room'
      path: '/waiting-room'
      fullPath: '/waiting-room'
      preLoaderRoute: typeof AuthenticatedWaitingRoomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recurrence': {
      id: '/_authenticated/recurrence'
      path: '/recurrence'
      fullPath: '/recurrence'
      preLoaderRoute: typeof AuthenticatedRecurrenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procedures': {
      id: '/_authenticated/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof AuthenticatedProceduresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial': {
      id: '/_authenticated/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof AuthenticatedFinancialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$id': {
      id: '/_authenticated/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthenticatedPatientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancialRoute: typeof AuthenticatedFinancialRoute
  AuthenticatedProceduresRoute: typeof AuthenticatedProceduresRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedRecurrenceRoute: typeof AuthenticatedRecurrenceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWaitingRoomRoute: typeof AuthenticatedWaitingRoomRoute
  AuthenticatedPatientsIdRoute: typeof AuthenticatedPatientsIdRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancialRoute: AuthenticatedFinancialRoute,
  AuthenticatedProceduresRoute: AuthenticatedProceduresRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedRecurrenceRoute: AuthenticatedRecurrenceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWaitingRoomRoute: AuthenticatedWaitingRoomRoute,
  AuthenticatedPatientsIdRoute: AuthenticatedPatientsIdRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
